[ERA-9328] i18n -- Adding Portuguese
PADAS/das-web-react pull request #1100
Opened 2024-03-18 17:36 UTC by JoshuaVulcan

### What does this PR do?
- Adds the Portuguese translations provided by volunteers

### Relevant link(s)
* Tracking tickets: [ERA-9328](https://allenai.atlassian.net/browse/ERA-9328)
* Env still building

[ERA-9328]: https://allenai.atlassian.net/browse/ERA-9328?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-04-01 14:58 UTC, fonzy911 commented
Hi @JoshuaVulcan. It seems that the UI is not reflecting the Portuguese translations.

![image](https://github.com/PADAS/das-web-react/assets/60930654/d074b66d-4e20-4e2c-bb87-441df7645a87)

I do see the components enabled but nothing reflected:

![image](https://github.com/PADAS/das-web-react/assets/60930654/2c86eeca-62df-4424-9830-62e44a61ea7d)

2024-04-01 17:15 UTC, luixlive requested changes

2024-04-01 17:15 UTC, luixlive commented on public/locales/pt/components.json
> +  "additembutton": {
The environment is not working as @fonzy911 mentioned cause the keys are not resolving. All of them were "lowercase-ed". For example this one should be `addItemButton`, not `additembutton` 👍

2024-04-03 19:55 UTC, JoshuaVulcan commented
Sorry y'all, I made a silly mistake with my conversion script to turn the spreadsheet pages into our translation files. Should be fixed now! @luixlive @fonzy911

2024-04-03 20:13 UTC, luixlive approved these changes

2024-04-03 21:31 UTC, fonzy911 reviewed
Hi @JoshuaVulcan, everything looks better now, thank you. It seems that the time slider part is also not translated in portuguese:

![image](https://github.com/PADAS/das-web-react/assets/60930654/bba5e002-9e38-4c5e-87e7-a284ab55d68d)

Also, it seems that the word "Events" and the actual events names are not being translated either:

![Screen Shot 2024-04-03 at 14 26 37](https://github.com/PADAS/das-web-react/assets/60930654/19361633-4bc3-4fd0-a5a1-7c8fb0e712f0)

2024-04-03 21:55 UTC, tiffanynwong commented
- Toast is not translated
![Screen Shot 2024-04-03 at 11 39 47 AM](https://github.com/PADAS/das-web-react/assets/87336082/afcee594-12b5-4a07-84e5-c153d548a6f1)

- "Event" button in event detail not translated (Portuguese, Spanish, and French)
![Screen Shot 2024-04-03 at 11 42 14 AM](https://github.com/PADAS/das-web-react/assets/87336082/bc072040-6660-475d-8fc4-0df05abc88cf)
- 404 on alert tab
![Screen Shot 2024-04-03 at 11 44 26 AM](https://github.com/PADAS/das-web-react/assets/87336082/69d7a2ac-c37c-4e9b-b63f-173d67b792ab)

- Timeslider control popup says "About 1 Month" (Portuguese & French)
![Screen Shot 2024-04-03 at 11 46 40 AM](https://github.com/PADAS/das-web-react/assets/87336082/96ade5b2-6b9e-4c16-a99b-523f32aefaa4)
- Should it say Portuguese (Brazil)? Or remove (United States) from the English option for consistency? 
![Screen Shot 2024-04-03 at 11 53 34 AM](https://github.com/PADAS/das-web-react/assets/87336082/8a047639-b9a9-4501-a7b4-cc1a82938619)

2024-04-08 16:25 UTC, luixlive commented
> * Should it say Portuguese (Brazil)? Or remove (United States) from the English option for consistency?
>   ![Screen Shot 2024-04-03 at 11 53 34 AM](https://private-user-images.githubusercontent.com/87336082/319369295-8a047639-b9a9-4501-a7b4-cc1a82938619.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1OTMyNjYsIm5iZiI6MTcxMjU5Mjk2NiwicGF0aCI6Ii84NzMzNjA4Mi8zMTkzNjkyOTUtOGEwNDc2MzktYjlhOS00NTAxLWE3YjQtY2MxYTgyOTM4NjE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDE2MTYwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkMzY3NzZiMDZkYzNiYjQxOWFkMDA2YjQxMzI3NTY3NTViNWE2YzA4Y2RhZDVmYTMxMTIyMTFkZWE2ZjA3NDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RPeiOWRqY7dp-ggJjweT2LhlUxV-eSj_M3aInSrFuBw)

About this, I think it makes sense to keep it as it is, or we can remove the `(United States)` for now. The thing is that english is localized to `en-US`, while Spanish, French and Portuguese are just `es`, `fr` and `pt`. The reasoning behind not localizing those is simply that I'd think that we will want to eventually localize english to different countries given the amount of users we have, in contrast to the other ones. But we can always change any of these configurations.

2024-04-08 18:39 UTC, luixlive commented
> * Timeslider control popup says "About 1 Month" (Portuguese & French)
>   ![Screen Shot 2024-04-03 at 11 46 40 AM](https://private-user-images.githubusercontent.com/87336082/319368518-96ade5b2-6b9e-4c16-a99b-523f32aefaa4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1OTMyNjYsIm5iZiI6MTcxMjU5Mjk2NiwicGF0aCI6Ii84NzMzNjA4Mi8zMTkzNjg1MTgtOTZhZGU1YjItNmI5ZS00YzE2LWE5OWItNTIzZjMyYWVmYWE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDE2MTYwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzOTYxOTU1ODIyYWViMTBmZDcyOWJlZmZmNmQ3NDJjOWZmNjg2NmY5NjQ0NzkwMWQ5Mjc3ZWIyOTg4NjI2NzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RxPN15kDhjOtQ-sRCdMCB1oJMAPk5CKA2tRfPwbb-5w)

I think this one should be taken as a separate bug ticket cause seems like it could be caused by something wrong going on with the automatic translation of the `calcFriendlyDurationString` method.

2024-04-08 20:16 UTC, fonzy911 commented
Hi @luixlive , thank you very much for the fixes, just a couple more things if I may. It seems that, for some reason, the method that calls the translated tooltip name for the timeslider, is not being called upon appropriately, cause it looks like this, instead of showing the actual translated name:

![image](https://github.com/PADAS/das-web-react/assets/60930654/853c04f3-e330-476f-8c67-ffb2ba9d2c7c)

Also, whenever we want to create either a new event or patrol, only half of the modal's fields appear to be translated as well, not sure if this goes out of the scope of this particular ticket:

2024-04-09 00:43 UTC, merged